;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	c-indent-line-or-region
	counsel-M-x
	delete-horizontal-space
	downcase-region
	haml-electric-backspace
	ivy-alt-done
	kill-region
	org-cycle
	org-return
	org-self-insert-command
	revert-buffer
	upcase-region
	web-mode-comment-or-uncomment
	yank-rectangle
	))

(setq mc/cmds-to-run-once
      '(
	counsel-find-file
	ivy-switch-buffer
	mouse-buffer-menu
	mouse-set-region
	tabbar-forward
	))
